- hosts: build-slave
  become: true
  tasks:
  - name: update ubuntu repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Install java
    apt:
      name: openjdk-17-jre
      state: present

  - name: Install Maven
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt

  - name: Extract Maven
    unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: Install docker
    apt:
      name: docker.io
      state: present
  - name: Start Docker service
    service:
      name: docker
      state: started
